Public Class frm_disclaimer

    'Public Shared disclaimer As String = "This program has been written based on the assumption that the user does not " + _
    '    "mix up Etabs / SAFE / SAP2000 model files with other documents / data files in the same folder. " + _
    '    "The program searches for model files (.edb, .$et, .sdb, .$2k, .fdb, .$sf) in a folder, " + _
    '    "note its name and treat all other files having the same name (and different extension) as files generated by the analysis " + _
    '    "process and display them. The user is completely responsible in all respects to review the results, carefully " + _
    '    "select files to delete before actually deleting. The programmer, advertiser, distributor or anybody " + _
    '    "else involved in the production and distribution of the program takes no responsibility, in any form, " + _
    '    "for any loss or harm to anybody resulted by use of this program." + _
    '    vbCrLf + vbCrLf + _
    '    "By the way, deleted files go into " + _
    '    "the Recycle Bin (If it is NOT FULL on your machine)."

    'Private Sub frm_disclaimer_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
    'lbl_disclaimer.Text = disclaimer
    'TextBox1.Text = disclaimer

    'End Sub

    Private Sub bttnOK_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles bttnOK.Click
        Me.Close()

    End Sub
End Class