Public Class frmAbout


    Public Shared program_name As String = "AFR (Analysis Files Remover)"
    Public Shared program_description As String = "Search and Delete Analysis / Run Files Generated by Software Programs SAP2000, Etabs, SAFE, CSI Bridge and STAAD.Pro"



    Private Sub frmAbout_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load

        lbl_program_title.Text = program_name

        lbl_program_description.Text = program_description

    End Sub

    Private Sub bttnOK_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles bttnOK.Click
        Me.Close()

    End Sub
End Class